### ISSUE TITLE
CKeditor unresponsive on IE9 with v2.5.5

### ISSUE THREAD

**Issue by peiledoir** [uploadcare/uploadcare-ckeditor#17]
Using the latest v2.5.5 makes the ckeditor unresponsive in IE9. It works with v2.4.0, but the rest of our site is using v2.5.5, so we'd like to try keep it all on the same version.

**Comment by dmitry-mukhin** [comment]
what exactly do you mean by unresponsive?

**Comment by peiledoir** [comment]
The dialog appears after clicking on the uploadcare button within the ckeditor, then once it appears, none of the tabs or buttons within the dialog are clickable. The page freezes and after approx half a minute, the initial click of a tab or button within the dialog is recognized. But it's extremely slow

**Comment by homm** [comment]
Could you provide some online demo? It would be nice to see it on http://jsbin.com or http://jsfiddle.net.

**Comment by khazamov** [comment]
@peiledoir Is this still an issue for you? Can you try installing uplodcare-ckeditor plugin on blank ckeditor v2.5.5 instance with no other plugins connected?
