### ISSUE TITLE
Doesn't works with multiple instances of Ckeditors on same web-page 

### ISSUE THREAD

**Issue by mahendra-rajput** [uploadcare/uploadcare-ckeditor#19]
Hello,
i am using multiple instances of ckeditors on single web page. All ckeditors includes uploadcare plugin. When i use uploadcare plugin to upload image on first editor, it inserts the image into the last instance of ckeditor.

Can you suggest a resolution for this?

Thank You!

**Comment by dmitry-mukhin** [comment]
Can you provide minimal JS|HTML to reproduce this?

**Comment by mahendra-rajput** [comment]
Yes,

Please find attached html and js files that i used for testing purpose.

Thank You!


[try.zip](https://github.com/uploadcare/uploadcare-ckeditor/files/263715/try.zip)

**Comment by mahendra-rajput** [comment]
hello, 

can you please let me know, if this issue can be solved?

**Comment by ZNick1982** [comment]
@mahendra-rajput Thank you for issue reporting and providing us example to reproduce it.
Now issue is solved and plugin is updated on ckEditor
To solve this on your site please update the Uploadcare plugin with version 2.1.5 from ckEditor.

**Comment by mahendra-rajput** [comment]
Great Job!

Issue solved.

Thank You So much!
