### ISSUE TITLE
Uploadcare 2.9.0 does not work with ckedtior

### ISSUE THREAD

**Issue by peiledoir** [uploadcare/uploadcare-ckeditor#20]
Stack trace
Line 8118 on uploadcare.full.js `throw new Error("No DOM elements found matching selector");`
Line 9459 in ckeditor `return b.getNative().createRange().item(0)`

**Comment by dmitry-mukhin** [comment]
Could you elaborate?

Just made this [simple demo](http://uploadcare.github.io/uploadcare-ckeditor/), everything works as expected (except icon).

Could you also tell what plugin and CKEditor versions are you using?

**Comment by dmitry-mukhin** [comment]
@peiledoir, I'll close this for now.
Feel free to reopen and provide more info, thanks!
