### ISSUE TITLE
Version: 4.7.1  ckeditor

### ISSUE THREAD

**Issue by ExoAnime** [uploadcare/uploadcare-ckeditor#26]
Hey, problem ckeditor  4.7.1?  not working... 

My plugins list.

richcombo
basicstyles
notificationaggregator
removeformat
lineutils
button
uploadwidget
colorbutton
toolbar
uploadimage
colordialog
fakeobjects
filetools
widget
link
youtube

**Comment by dmitry-mukhin** [comment]
"not working" does not help us.
can you elaborate please? also, try to use vanilla ckeditor with only Uploadcare plugin to rule out conflicts?
