### ISSUE TITLE
Updating to version 3.1.0

### ISSUE THREAD

**Issue by oleteacher** [uploadcare/uploadcare-ckeditor#27]
Greetings!

Wondering when plugin will be updated to version 3.1.0? Wish to include in software project but like to have latest version.

Thank you.

**Comment by oleteacher** [comment]
We have found another content provider affiliate program for our software. Maybe check back later.

**Comment by dmitry-mukhin** [comment]
just for the record, you can set the widget version explicitly, without waiting for plugin update.
